# Network settings
server.host: 0.0.0.0

# Elasticsearch settings
elasticsearch.hosts: ["https://elasticsearch:9200"]

# SSL settings
server.ssl.enabled: true
server.ssl.certificate: /certs/kibana.crt
server.ssl.key: /certs/kibana.key
server.ssl.certificateAuthorities: [ "/certs/ca.crt" ]

## X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: changeme
elasticsearch.ssl.certificateAuthorities: [ "/certs/ca.crt" ]
